<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Razin-Anik" ignored="0" name="signup testing" tests="8" failures="1" timestamp="23 Apr 2020 00:43:22 GMT" time="17.073" errors="0">
  <testcase name="atest" time="0.011" classname="scripts.codeRun"/>
  <testcase name="btest" time="0.002" classname="scripts.codeRun"/>
  <testcase name="ctest" time="0.003" classname="scripts.codeRun"/>
  <testcase name="validateElementPresent" time="4.261" classname="scripts.elementCheck"/>
  <testcase name="validateUrl" time="0.001" classname="scripts.testRun"/>
  <testcase name="validateMessangerURL" time="3.428" classname="scripts.elementCheck">
    <failure type="java.lang.AssertionError" message="expected [https://www.mess.com/] but found [https://www.messenger.com/]">
      <![CDATA[java.lang.AssertionError: expected [https://www.mess.com/] but found [https://www.messenger.com/]
	at scripts.elementCheck.validateMessangerURL(elementCheck.java:59)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- validateMessangerURL -->
  <testcase name="validateTitle" time="0.002" classname="scripts.testRun"/>
  <testcase name="validateTextPresnt" time="0.003" classname="scripts.testRun"/>
</testsuite> <!-- signup testing -->
